using System.CommandLine;

namespace PVAnalyze.Commands;

public static class CleanCommand
{
    public static Command Create()
    {
        var pathArg = new Argument<string>("path", "Path to a .nettrace file or directory containing traces");

        var command = new Command("clean", "Remove cached .etlx files generated by pvanalyze")
        {
            pathArg
        };

        command.SetHandler(Execute, pathArg);
        return command;
    }

    private static void Execute(string path)
    {
        var etlxFiles = new List<string>();

        if (Directory.Exists(path))
        {
            etlxFiles.AddRange(Directory.GetFiles(path, "*.pvanalyze.etlx"));
            etlxFiles.AddRange(Directory.GetFiles(path, "*.pvanalyze.etlx.lock"));
            etlxFiles.AddRange(Directory.GetFiles(path, "*.pvanalyze.etlx.tmp*"));
        }
        else if (File.Exists(path))
        {
            var etlxPath = path + ".pvanalyze.etlx";
            var lockPath = etlxPath + ".lock";
            if (File.Exists(etlxPath))
                etlxFiles.Add(etlxPath);

            if (File.Exists(lockPath))
                etlxFiles.Add(lockPath);

            var directory = Path.GetDirectoryName(path) ?? ".";
            var fileName = Path.GetFileName(path);
            etlxFiles.AddRange(Directory.GetFiles(directory, $"{fileName}.pvanalyze.etlx.tmp*"));

            if (etlxFiles.Count == 0)
                Console.Error.WriteLine($"No cached .etlx file found for: {path}");
        }
        else
        {
            Console.Error.WriteLine($"Path not found: {path}");
            return;
        }

        if (etlxFiles.Count == 0)
        {
            Console.WriteLine("No .etlx files to clean.");
            return;
        }

        long totalBytes = 0;
        int deleted = 0;

        foreach (var file in etlxFiles)
        {
            try
            {
                var size = new FileInfo(file).Length;
                File.Delete(file);
                totalBytes += size;
                deleted++;
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"Failed to delete {file}: {ex.Message}");
            }
        }

        Console.WriteLine($"Removed {deleted} .etlx file(s), freed {totalBytes / (1024.0 * 1024.0):F1} MB.");
    }
}
